version: '3.8'

services:
  minio:
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    container_name: ${MINIO_CONTAINER_NAME:-masterbase_minio}
    restart: always
    env_file:
      - vars.env
    ports:
      - "9000:9000"
    volumes:
      - ${MINIO_VOLUME_NAME:-demo_data}:/blobs/

  db:
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    container_name: ${DB_CONTAINER_NAME:-masterbase_db}
    restart: always
    env_file:
      - vars.env
    environment:
      POSTGRES_DB: demos
    ports:
      - "8050:5432"
    volumes:
      - ${DB_VOLUME_NAME:-db_data}:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      args:
        DEVELOPMENT: ${DEVELOPMENT:-false}
    container_name: ${API_CONTAINER_NAME:-masterbase_api}
    restart: always
    env_file:
      - vars.env
    environment:
      POSTGRES_HOST: db
      MINIO_HOST: minio
    ports:
      - "8000:8000"
    volumes:
      - ${ANALYSIS_BINARY}:/analysis-binary:ro
    depends_on:
      - minio


networks:
  ${NETWORK_NAME:-network}:
    driver: bridge

volumes:
  ${MINIO_VOLUME_NAME:-demo_data}:
  ${DB_VOLUME_NAME:-db_data}: