services:
  minio:
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    container_name: ${MINIO_CONTAINER_NAME:-masterbase_minio}
    restart: always
    env_file:
      - .env
    ports:
      - "${MINIO_PORT:-9000}:9000"
    volumes:
      - demo_data:/blobs/
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    container_name: ${DB_CONTAINER_NAME:-masterbase_db}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: demos
    ports:
      - "${POSTGRES_PORT:-8050}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      args:
        DEVELOPMENT: ${DEVELOPMENT:-false}
    container_name: ${API_CONTAINER_NAME:-masterbase_api}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT_INTERNAL: 5432
      MINIO_HOST: minio
      MINIO_PORT_INTERNAL: 9000
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ${ANALYSIS_BINARY}:/analysis-binary:ro
    depends_on:
      minio:
        condition: service_healthy
      db:
        condition: service_healthy


networks:
  network:
    driver: bridge

volumes:
  demo_data:
  db_data: