services:
  minio:
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    container_name: ${MINIO_CONTAINER_NAME:-masterbase_minio}
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - demo_data:/blobs/

  db:
    build:
      context: .
      dockerfile: ./services/db/Dockerfile
    container_name: ${DB_CONTAINER_NAME:-masterbase_db}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: demos
    ports:
      - "8050:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      args:
        DEVELOPMENT: ${DEVELOPMENT:-false}
    container_name: ${API_CONTAINER_NAME:-masterbase_api}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      MINIO_HOST: minio
    ports:
      - "8000:8000"
    volumes:
      - ${ANALYSIS_BINARY}:/analysis-binary:ro
    depends_on:
      - minio
      - db


networks:
  network:
    driver: bridge

volumes:
  demo_data:
  db_data: